branches:
  only:
    - master

language: go

go: "1.11.2"

services:
  - postgresql

postgres:
  adapter: postgresql
  username: postgres
  password: postgres

before_script:
  - psql -U postgres -f ./dbconfig/db_create.sql

script:
  - go test -v ./...