CREATE DATABASE Commendeer
	WITH
	ENCODING = 'UTF8'
	CONNECTION LIMIT = -1;

\c commendeer

CREATE TABLE IF NOT EXISTS Questionnaire (
	QuestionnaireID SERIAL PRIMARY KEY,
	Title TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS AccessCode (
	CodeID SERIAL PRIMARY KEY,
	Email VARCHAR(150),
	SystemUsername VARCHAR(50) NOT NULL,
	Code VARCHAR(10),
	Used BOOL NOT NULL,
	QuestionnaireID INTEGER REFERENCES Questionnaire(QuestionnaireID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS UserInfo (
	UserID SERIAL PRIMARY KEY,
	Username VARCHAR(50) NOT NULL,
	Pass VARCHAR(500) NOT NULL,
	Administrator BOOL NOT NULL,
	Salt VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS QuestionType (
	QuestionTypeID SERIAL PRIMARY KEY,
	Description TEXT
);

CREATE TABLE IF NOT EXISTS Question (
	QuestionID SERIAL PRIMARY KEY,
	QuestionTypeID INTEGER REFERENCES QuestionType(QuestionTypeID) ON DELETE CASCADE,
	QuestionOrder INTEGER,
	Title TEXT NOT NULL,
	QuestionnaireID INTEGER REFERENCES Questionnaire(QuestionnaireID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS MultiChoiceQuestionOption (
	MultiChoiceQuestionOptionID SERIAL PRIMARY KEY,
	QuestionID INTEGER REFERENCES Question(QuestionID) ON DELETE CASCADE,
	OptionDescription TEXT
);

CREATE TABLE IF NOT EXISTS MultiChoiceQuestionOption_Result (
	MultiChoiceQuestionOption_ResultID SERIAL PRIMARY KEY,
	QuestionID INTEGER REFERENCES Question(QuestionID) ON DELETE CASCADE,
	MultiChoiceQuestionOptionID INTEGER REFERENCES MultiChoiceQuestionOption(MultiChoiceQuestionOptionID) ON DELETE CASCADE,
	CodeID INTEGER REFERENCES AccessCode(CodeID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Question_Result (
	Question_ResultID SERIAL PRIMARY KEY,
	QuestionID INTEGER REFERENCES Question(QuestionID) ON DELETE CASCADE,
	CodeID INTEGER REFERENCES AccessCode(CodeID) ON DELETE CASCADE,
	Answer TEXT
);

CREATE TABLE IF NOT EXISTS AuthCodes (
	AuthCodeID SERIAL PRIMARY KEY,
	UserID INTEGER REFERENCES UserInfo(UserID) ON DELETE CASCADE,
	Code VARCHAR(20) NOT NULL,
	Administrator BOOL NOT NULL
);