// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Error int32

const (
	Error_NIL                Error = 0
	Error_OK                 Error = 200
	Error_CREATED            Error = 201
	Error_ACCEPTED           Error = 202
	Error_BADREQUEST         Error = 400
	Error_FORBIDDEN          Error = 403
	Error_NOTFOUND           Error = 404
	Error_NOTACCEPTABLE      Error = 406
	Error_INTERNALERROR      Error = 500
	Error_SERVICEUNAVAILABLE Error = 503
)

var Error_name = map[int32]string{
	0:   "NIL",
	200: "OK",
	201: "CREATED",
	202: "ACCEPTED",
	400: "BADREQUEST",
	403: "FORBIDDEN",
	404: "NOTFOUND",
	406: "NOTACCEPTABLE",
	500: "INTERNALERROR",
	503: "SERVICEUNAVAILABLE",
}
var Error_value = map[string]int32{
	"NIL":                0,
	"OK":                 200,
	"CREATED":            201,
	"ACCEPTED":           202,
	"BADREQUEST":         400,
	"FORBIDDEN":          403,
	"NOTFOUND":           404,
	"NOTACCEPTABLE":      406,
	"INTERNALERROR":      500,
	"SERVICEUNAVAILABLE": 503,
}

func (x Error) String() string {
	return proto.EnumName(Error_name, int32(x))
}
func (Error) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_service_09f70c9338aec2b2, []int{0}
}

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_09f70c9338aec2b2, []int{0}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (dst *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(dst, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Authcode             string   `protobuf:"bytes,2,opt,name=authcode,proto3" json:"authcode,omitempty"`
	Error                Error    `protobuf:"varint,3,opt,name=error,proto3,enum=pb.Error" json:"error,omitempty"`
	ErrorDetails         string   `protobuf:"bytes,4,opt,name=errorDetails,proto3" json:"errorDetails,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_09f70c9338aec2b2, []int{1}
}
func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (dst *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(dst, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginResponse) GetAuthcode() string {
	if m != nil {
		return m.Authcode
	}
	return ""
}

func (m *LoginResponse) GetError() Error {
	if m != nil {
		return m.Error
	}
	return Error_NIL
}

func (m *LoginResponse) GetErrorDetails() string {
	if m != nil {
		return m.ErrorDetails
	}
	return ""
}

type LogoutRequest struct {
	Authcode             string   `protobuf:"bytes,1,opt,name=authcode,proto3" json:"authcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_09f70c9338aec2b2, []int{2}
}
func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (dst *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(dst, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

func (m *LogoutRequest) GetAuthcode() string {
	if m != nil {
		return m.Authcode
	}
	return ""
}

type LogoutResponse struct {
	Error                Error    `protobuf:"varint,1,opt,name=error,proto3,enum=pb.Error" json:"error,omitempty"`
	ErrorDetails         string   `protobuf:"bytes,2,opt,name=errorDetails,proto3" json:"errorDetails,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_09f70c9338aec2b2, []int{3}
}
func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (dst *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(dst, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

func (m *LogoutResponse) GetError() Error {
	if m != nil {
		return m.Error
	}
	return Error_NIL
}

func (m *LogoutResponse) GetErrorDetails() string {
	if m != nil {
		return m.ErrorDetails
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "pb.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "pb.LoginResponse")
	proto.RegisterType((*LogoutRequest)(nil), "pb.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "pb.LogoutResponse")
	proto.RegisterEnum("pb.Error", Error_name, Error_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommendeerClient is the client API for Commendeer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommendeerClient interface {
	// Logs user in, creates an authentication code for later authentication
	LoginUser(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	LogoutUser(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
}

type commendeerClient struct {
	cc *grpc.ClientConn
}

func NewCommendeerClient(cc *grpc.ClientConn) CommendeerClient {
	return &commendeerClient{cc}
}

func (c *commendeerClient) LoginUser(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/pb.Commendeer/LoginUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commendeerClient) LogoutUser(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, "/pb.Commendeer/LogoutUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommendeerServer is the server API for Commendeer service.
type CommendeerServer interface {
	// Logs user in, creates an authentication code for later authentication
	LoginUser(context.Context, *LoginRequest) (*LoginResponse, error)
	LogoutUser(context.Context, *LogoutRequest) (*LogoutResponse, error)
}

func RegisterCommendeerServer(s *grpc.Server, srv CommendeerServer) {
	s.RegisterService(&_Commendeer_serviceDesc, srv)
}

func _Commendeer_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommendeerServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Commendeer/LoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommendeerServer).LoginUser(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Commendeer_LogoutUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommendeerServer).LogoutUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Commendeer/LogoutUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommendeerServer).LogoutUser(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Commendeer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Commendeer",
	HandlerType: (*CommendeerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginUser",
			Handler:    _Commendeer_LoginUser_Handler,
		},
		{
			MethodName: "LogoutUser",
			Handler:    _Commendeer_LogoutUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_service_09f70c9338aec2b2) }

var fileDescriptor_service_09f70c9338aec2b2 = []byte{
	// 398 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xed, 0xc6, 0x94, 0xd4, 0xa3, 0x38, 0x2c, 0x73, 0xc1, 0xca, 0x85, 0xca, 0xa7, 0x0a, 0xa4,
	0x1c, 0x82, 0xf8, 0x00, 0xc7, 0xde, 0x48, 0x16, 0xd6, 0x1a, 0xb6, 0x76, 0xef, 0x4e, 0xb3, 0x82,
	0x48, 0xc4, 0x6b, 0x76, 0x6d, 0xfa, 0x13, 0x1c, 0x90, 0x40, 0xfc, 0x02, 0xbf, 0x02, 0x7c, 0x0f,
	0x12, 0x57, 0xe4, 0x75, 0x1d, 0x5c, 0x71, 0x80, 0x9b, 0xdf, 0xdb, 0x37, 0x6f, 0xde, 0x8c, 0x07,
	0x3c, 0x23, 0xf5, 0xfb, 0xfd, 0xb5, 0x5c, 0xd6, 0x5a, 0x35, 0x0a, 0x27, 0xf5, 0x36, 0xd8, 0xc0,
	0x2c, 0x55, 0xaf, 0xf7, 0x95, 0x90, 0xef, 0x5a, 0x69, 0x1a, 0x5c, 0xc0, 0x59, 0x6b, 0xa4, 0xae,
	0xca, 0x83, 0xf4, 0xc9, 0x39, 0xb9, 0x70, 0xc5, 0x11, 0x77, 0x6f, 0x75, 0x69, 0xcc, 0x8d, 0xd2,
	0x3b, 0x7f, 0xd2, 0xbf, 0x0d, 0x38, 0xf8, 0x40, 0xc0, 0xbb, 0x35, 0x32, 0xb5, 0xaa, 0x8c, 0xfc,
	0x97, 0x53, 0xd9, 0x36, 0x6f, 0xae, 0xd5, 0x4e, 0x0e, 0x4e, 0x03, 0xc6, 0xc7, 0x70, 0x2a, 0xb5,
	0x56, 0xda, 0x77, 0xce, 0xc9, 0xc5, 0x7c, 0xe5, 0x2e, 0xeb, 0xed, 0x92, 0x75, 0x84, 0xe8, 0x79,
	0x0c, 0x60, 0x66, 0x3f, 0x62, 0xd9, 0x94, 0xfb, 0xb7, 0xc6, 0xbf, 0x67, 0x0d, 0xee, 0x70, 0xc1,
	0x53, 0x9b, 0x46, 0xb5, 0xcd, 0x68, 0xae, 0x63, 0x47, 0x72, 0xb7, 0x63, 0x50, 0xc0, 0x7c, 0x10,
	0xdf, 0x66, 0x3f, 0x66, 0x20, 0xff, 0x99, 0x61, 0xf2, 0x77, 0x86, 0x27, 0x5f, 0x09, 0x9c, 0xda,
	0x22, 0x9c, 0x82, 0xc3, 0x93, 0x94, 0x9e, 0xe0, 0x14, 0x26, 0xd9, 0x0b, 0xfa, 0x8d, 0xe0, 0x0c,
	0xa6, 0x91, 0x60, 0x61, 0xce, 0x62, 0xfa, 0x9d, 0xa0, 0x07, 0x67, 0x61, 0x14, 0xb1, 0x97, 0x1d,
	0xfc, 0x41, 0xf0, 0x01, 0xc0, 0x3a, 0x8c, 0x05, 0x7b, 0x55, 0xb0, 0xcb, 0x9c, 0x7e, 0x74, 0x70,
	0x0e, 0xee, 0x26, 0x13, 0xeb, 0x24, 0x8e, 0x19, 0xa7, 0x9f, 0x9c, 0x4e, 0xcf, 0xb3, 0x7c, 0x93,
	0x15, 0x3c, 0xa6, 0x9f, 0x1d, 0x44, 0xf0, 0x78, 0x96, 0xf7, 0x0e, 0xe1, 0x3a, 0x65, 0xf4, 0x8b,
	0xe5, 0x12, 0x9e, 0x33, 0xc1, 0xc3, 0x94, 0x09, 0x91, 0x09, 0xfa, 0xd3, 0xc1, 0x47, 0x80, 0x97,
	0x4c, 0x5c, 0x25, 0x11, 0x2b, 0x78, 0x78, 0x15, 0x26, 0xa9, 0x15, 0xff, 0x72, 0x56, 0x37, 0x00,
	0x91, 0x3a, 0x1c, 0x64, 0xb5, 0x93, 0x52, 0xe3, 0x0a, 0x5c, 0xfb, 0x27, 0x0b, 0x23, 0x35, 0xd2,
	0x6e, 0xf4, 0xf1, 0x85, 0x2c, 0x1e, 0x8e, 0x98, 0x7e, 0x5d, 0xc1, 0x09, 0x3e, 0x07, 0xe8, 0x57,
	0x68, 0x8b, 0x06, 0xc9, 0x9f, 0xfd, 0x2f, 0x70, 0x4c, 0x0d, 0x65, 0xdb, 0xfb, 0xf6, 0x10, 0x9f,
	0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x79, 0xa3, 0xd3, 0x99, 0x02, 0x00, 0x00,
}
