// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Error int32

const (
	Error_NIL                Error = 0
	Error_OK                 Error = 200
	Error_CREATED            Error = 201
	Error_ACCEPTED           Error = 202
	Error_BADREQUEST         Error = 400
	Error_FORBIDDEN          Error = 403
	Error_NOTFOUND           Error = 404
	Error_NOTACCEPTABLE      Error = 406
	Error_INTERNALERROR      Error = 500
	Error_SERVICEUNAVAILABLE Error = 503
)

var Error_name = map[int32]string{
	0:   "NIL",
	200: "OK",
	201: "CREATED",
	202: "ACCEPTED",
	400: "BADREQUEST",
	403: "FORBIDDEN",
	404: "NOTFOUND",
	406: "NOTACCEPTABLE",
	500: "INTERNALERROR",
	503: "SERVICEUNAVAILABLE",
}
var Error_value = map[string]int32{
	"NIL":                0,
	"OK":                 200,
	"CREATED":            201,
	"ACCEPTED":           202,
	"BADREQUEST":         400,
	"FORBIDDEN":          403,
	"NOTFOUND":           404,
	"NOTACCEPTABLE":      406,
	"INTERNALERROR":      500,
	"SERVICEUNAVAILABLE": 503,
}

func (x Error) String() string {
	return proto.EnumName(Error_name, int32(x))
}
func (Error) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_service_21dd3ab72bafd08f, []int{0}
}

type CreateCodeRequest struct {
	Authcode             string   `protobuf:"bytes,1,opt,name=authcode,proto3" json:"authcode,omitempty"`
	QuestionnaireID      int32    `protobuf:"varint,2,opt,name=questionnaireID,proto3" json:"questionnaireID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCodeRequest) Reset()         { *m = CreateCodeRequest{} }
func (m *CreateCodeRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCodeRequest) ProtoMessage()    {}
func (*CreateCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_21dd3ab72bafd08f, []int{0}
}
func (m *CreateCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCodeRequest.Unmarshal(m, b)
}
func (m *CreateCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCodeRequest.Marshal(b, m, deterministic)
}
func (dst *CreateCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCodeRequest.Merge(dst, src)
}
func (m *CreateCodeRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCodeRequest.Size(m)
}
func (m *CreateCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCodeRequest proto.InternalMessageInfo

func (m *CreateCodeRequest) GetAuthcode() string {
	if m != nil {
		return m.Authcode
	}
	return ""
}

func (m *CreateCodeRequest) GetQuestionnaireID() int32 {
	if m != nil {
		return m.QuestionnaireID
	}
	return 0
}

type CreateCodeResponse struct {
	Error                Error    `protobuf:"varint,1,opt,name=error,proto3,enum=pb.Error" json:"error,omitempty"`
	ErrorDetails         string   `protobuf:"bytes,2,opt,name=errorDetails,proto3" json:"errorDetails,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCodeResponse) Reset()         { *m = CreateCodeResponse{} }
func (m *CreateCodeResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCodeResponse) ProtoMessage()    {}
func (*CreateCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_21dd3ab72bafd08f, []int{1}
}
func (m *CreateCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCodeResponse.Unmarshal(m, b)
}
func (m *CreateCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCodeResponse.Marshal(b, m, deterministic)
}
func (dst *CreateCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCodeResponse.Merge(dst, src)
}
func (m *CreateCodeResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCodeResponse.Size(m)
}
func (m *CreateCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCodeResponse proto.InternalMessageInfo

func (m *CreateCodeResponse) GetError() Error {
	if m != nil {
		return m.Error
	}
	return Error_NIL
}

func (m *CreateCodeResponse) GetErrorDetails() string {
	if m != nil {
		return m.ErrorDetails
	}
	return ""
}

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_21dd3ab72bafd08f, []int{2}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (dst *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(dst, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Authcode             string   `protobuf:"bytes,2,opt,name=authcode,proto3" json:"authcode,omitempty"`
	Error                Error    `protobuf:"varint,3,opt,name=error,proto3,enum=pb.Error" json:"error,omitempty"`
	ErrorDetails         string   `protobuf:"bytes,4,opt,name=errorDetails,proto3" json:"errorDetails,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_21dd3ab72bafd08f, []int{3}
}
func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (dst *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(dst, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginResponse) GetAuthcode() string {
	if m != nil {
		return m.Authcode
	}
	return ""
}

func (m *LoginResponse) GetError() Error {
	if m != nil {
		return m.Error
	}
	return Error_NIL
}

func (m *LoginResponse) GetErrorDetails() string {
	if m != nil {
		return m.ErrorDetails
	}
	return ""
}

type LogoutRequest struct {
	Authcode             string   `protobuf:"bytes,1,opt,name=authcode,proto3" json:"authcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_21dd3ab72bafd08f, []int{4}
}
func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (dst *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(dst, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

func (m *LogoutRequest) GetAuthcode() string {
	if m != nil {
		return m.Authcode
	}
	return ""
}

type LogoutResponse struct {
	Error                Error    `protobuf:"varint,1,opt,name=error,proto3,enum=pb.Error" json:"error,omitempty"`
	ErrorDetails         string   `protobuf:"bytes,2,opt,name=errorDetails,proto3" json:"errorDetails,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_21dd3ab72bafd08f, []int{5}
}
func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (dst *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(dst, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

func (m *LogoutResponse) GetError() Error {
	if m != nil {
		return m.Error
	}
	return Error_NIL
}

func (m *LogoutResponse) GetErrorDetails() string {
	if m != nil {
		return m.ErrorDetails
	}
	return ""
}

type DateQuestion struct {
	Order                int32    `protobuf:"varint,1,opt,name=order,proto3" json:"order,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DateQuestion) Reset()         { *m = DateQuestion{} }
func (m *DateQuestion) String() string { return proto.CompactTextString(m) }
func (*DateQuestion) ProtoMessage()    {}
func (*DateQuestion) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_21dd3ab72bafd08f, []int{6}
}
func (m *DateQuestion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DateQuestion.Unmarshal(m, b)
}
func (m *DateQuestion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DateQuestion.Marshal(b, m, deterministic)
}
func (dst *DateQuestion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DateQuestion.Merge(dst, src)
}
func (m *DateQuestion) XXX_Size() int {
	return xxx_messageInfo_DateQuestion.Size(m)
}
func (m *DateQuestion) XXX_DiscardUnknown() {
	xxx_messageInfo_DateQuestion.DiscardUnknown(m)
}

var xxx_messageInfo_DateQuestion proto.InternalMessageInfo

func (m *DateQuestion) GetOrder() int32 {
	if m != nil {
		return m.Order
	}
	return 0
}

func (m *DateQuestion) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type ShortTextQuestion struct {
	Order                int32    `protobuf:"varint,1,opt,name=order,proto3" json:"order,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShortTextQuestion) Reset()         { *m = ShortTextQuestion{} }
func (m *ShortTextQuestion) String() string { return proto.CompactTextString(m) }
func (*ShortTextQuestion) ProtoMessage()    {}
func (*ShortTextQuestion) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_21dd3ab72bafd08f, []int{7}
}
func (m *ShortTextQuestion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShortTextQuestion.Unmarshal(m, b)
}
func (m *ShortTextQuestion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShortTextQuestion.Marshal(b, m, deterministic)
}
func (dst *ShortTextQuestion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShortTextQuestion.Merge(dst, src)
}
func (m *ShortTextQuestion) XXX_Size() int {
	return xxx_messageInfo_ShortTextQuestion.Size(m)
}
func (m *ShortTextQuestion) XXX_DiscardUnknown() {
	xxx_messageInfo_ShortTextQuestion.DiscardUnknown(m)
}

var xxx_messageInfo_ShortTextQuestion proto.InternalMessageInfo

func (m *ShortTextQuestion) GetOrder() int32 {
	if m != nil {
		return m.Order
	}
	return 0
}

func (m *ShortTextQuestion) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type LongTextQuestion struct {
	Order                int32    `protobuf:"varint,1,opt,name=order,proto3" json:"order,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LongTextQuestion) Reset()         { *m = LongTextQuestion{} }
func (m *LongTextQuestion) String() string { return proto.CompactTextString(m) }
func (*LongTextQuestion) ProtoMessage()    {}
func (*LongTextQuestion) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_21dd3ab72bafd08f, []int{8}
}
func (m *LongTextQuestion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongTextQuestion.Unmarshal(m, b)
}
func (m *LongTextQuestion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongTextQuestion.Marshal(b, m, deterministic)
}
func (dst *LongTextQuestion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongTextQuestion.Merge(dst, src)
}
func (m *LongTextQuestion) XXX_Size() int {
	return xxx_messageInfo_LongTextQuestion.Size(m)
}
func (m *LongTextQuestion) XXX_DiscardUnknown() {
	xxx_messageInfo_LongTextQuestion.DiscardUnknown(m)
}

var xxx_messageInfo_LongTextQuestion proto.InternalMessageInfo

func (m *LongTextQuestion) GetOrder() int32 {
	if m != nil {
		return m.Order
	}
	return 0
}

func (m *LongTextQuestion) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type AnswerOption struct {
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnswerOption) Reset()         { *m = AnswerOption{} }
func (m *AnswerOption) String() string { return proto.CompactTextString(m) }
func (*AnswerOption) ProtoMessage()    {}
func (*AnswerOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_21dd3ab72bafd08f, []int{9}
}
func (m *AnswerOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnswerOption.Unmarshal(m, b)
}
func (m *AnswerOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnswerOption.Marshal(b, m, deterministic)
}
func (dst *AnswerOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnswerOption.Merge(dst, src)
}
func (m *AnswerOption) XXX_Size() int {
	return xxx_messageInfo_AnswerOption.Size(m)
}
func (m *AnswerOption) XXX_DiscardUnknown() {
	xxx_messageInfo_AnswerOption.DiscardUnknown(m)
}

var xxx_messageInfo_AnswerOption proto.InternalMessageInfo

func (m *AnswerOption) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type RadioQuestion struct {
	Order                int32           `protobuf:"varint,1,opt,name=order,proto3" json:"order,omitempty"`
	Title                string          `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Options              []*AnswerOption `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RadioQuestion) Reset()         { *m = RadioQuestion{} }
func (m *RadioQuestion) String() string { return proto.CompactTextString(m) }
func (*RadioQuestion) ProtoMessage()    {}
func (*RadioQuestion) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_21dd3ab72bafd08f, []int{10}
}
func (m *RadioQuestion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RadioQuestion.Unmarshal(m, b)
}
func (m *RadioQuestion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RadioQuestion.Marshal(b, m, deterministic)
}
func (dst *RadioQuestion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RadioQuestion.Merge(dst, src)
}
func (m *RadioQuestion) XXX_Size() int {
	return xxx_messageInfo_RadioQuestion.Size(m)
}
func (m *RadioQuestion) XXX_DiscardUnknown() {
	xxx_messageInfo_RadioQuestion.DiscardUnknown(m)
}

var xxx_messageInfo_RadioQuestion proto.InternalMessageInfo

func (m *RadioQuestion) GetOrder() int32 {
	if m != nil {
		return m.Order
	}
	return 0
}

func (m *RadioQuestion) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *RadioQuestion) GetOptions() []*AnswerOption {
	if m != nil {
		return m.Options
	}
	return nil
}

type MultiChoiceQuestion struct {
	Order                int32           `protobuf:"varint,1,opt,name=order,proto3" json:"order,omitempty"`
	Title                string          `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Options              []*AnswerOption `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MultiChoiceQuestion) Reset()         { *m = MultiChoiceQuestion{} }
func (m *MultiChoiceQuestion) String() string { return proto.CompactTextString(m) }
func (*MultiChoiceQuestion) ProtoMessage()    {}
func (*MultiChoiceQuestion) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_21dd3ab72bafd08f, []int{11}
}
func (m *MultiChoiceQuestion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiChoiceQuestion.Unmarshal(m, b)
}
func (m *MultiChoiceQuestion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiChoiceQuestion.Marshal(b, m, deterministic)
}
func (dst *MultiChoiceQuestion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiChoiceQuestion.Merge(dst, src)
}
func (m *MultiChoiceQuestion) XXX_Size() int {
	return xxx_messageInfo_MultiChoiceQuestion.Size(m)
}
func (m *MultiChoiceQuestion) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiChoiceQuestion.DiscardUnknown(m)
}

var xxx_messageInfo_MultiChoiceQuestion proto.InternalMessageInfo

func (m *MultiChoiceQuestion) GetOrder() int32 {
	if m != nil {
		return m.Order
	}
	return 0
}

func (m *MultiChoiceQuestion) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MultiChoiceQuestion) GetOptions() []*AnswerOption {
	if m != nil {
		return m.Options
	}
	return nil
}

type CreateFormRequest struct {
	Title                string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	ShortTextQuestions   []*ShortTextQuestion   `protobuf:"bytes,2,rep,name=shortTextQuestions,proto3" json:"shortTextQuestions,omitempty"`
	LongTextQuestions    []*LongTextQuestion    `protobuf:"bytes,3,rep,name=longTextQuestions,proto3" json:"longTextQuestions,omitempty"`
	MultiChoiceQuestions []*MultiChoiceQuestion `protobuf:"bytes,4,rep,name=multiChoiceQuestions,proto3" json:"multiChoiceQuestions,omitempty"`
	RadioQuestions       []*RadioQuestion       `protobuf:"bytes,5,rep,name=radioQuestions,proto3" json:"radioQuestions,omitempty"`
	DateQuestions        []*DateQuestion        `protobuf:"bytes,6,rep,name=dateQuestions,proto3" json:"dateQuestions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CreateFormRequest) Reset()         { *m = CreateFormRequest{} }
func (m *CreateFormRequest) String() string { return proto.CompactTextString(m) }
func (*CreateFormRequest) ProtoMessage()    {}
func (*CreateFormRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_21dd3ab72bafd08f, []int{12}
}
func (m *CreateFormRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFormRequest.Unmarshal(m, b)
}
func (m *CreateFormRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFormRequest.Marshal(b, m, deterministic)
}
func (dst *CreateFormRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFormRequest.Merge(dst, src)
}
func (m *CreateFormRequest) XXX_Size() int {
	return xxx_messageInfo_CreateFormRequest.Size(m)
}
func (m *CreateFormRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFormRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFormRequest proto.InternalMessageInfo

func (m *CreateFormRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateFormRequest) GetShortTextQuestions() []*ShortTextQuestion {
	if m != nil {
		return m.ShortTextQuestions
	}
	return nil
}

func (m *CreateFormRequest) GetLongTextQuestions() []*LongTextQuestion {
	if m != nil {
		return m.LongTextQuestions
	}
	return nil
}

func (m *CreateFormRequest) GetMultiChoiceQuestions() []*MultiChoiceQuestion {
	if m != nil {
		return m.MultiChoiceQuestions
	}
	return nil
}

func (m *CreateFormRequest) GetRadioQuestions() []*RadioQuestion {
	if m != nil {
		return m.RadioQuestions
	}
	return nil
}

func (m *CreateFormRequest) GetDateQuestions() []*DateQuestion {
	if m != nil {
		return m.DateQuestions
	}
	return nil
}

type CreateResponse struct {
	Error                Error    `protobuf:"varint,1,opt,name=error,proto3,enum=pb.Error" json:"error,omitempty"`
	ErrorDetails         string   `protobuf:"bytes,2,opt,name=errorDetails,proto3" json:"errorDetails,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_21dd3ab72bafd08f, []int{13}
}
func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (dst *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(dst, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetError() Error {
	if m != nil {
		return m.Error
	}
	return Error_NIL
}

func (m *CreateResponse) GetErrorDetails() string {
	if m != nil {
		return m.ErrorDetails
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateCodeRequest)(nil), "pb.CreateCodeRequest")
	proto.RegisterType((*CreateCodeResponse)(nil), "pb.CreateCodeResponse")
	proto.RegisterType((*LoginRequest)(nil), "pb.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "pb.LoginResponse")
	proto.RegisterType((*LogoutRequest)(nil), "pb.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "pb.LogoutResponse")
	proto.RegisterType((*DateQuestion)(nil), "pb.DateQuestion")
	proto.RegisterType((*ShortTextQuestion)(nil), "pb.ShortTextQuestion")
	proto.RegisterType((*LongTextQuestion)(nil), "pb.LongTextQuestion")
	proto.RegisterType((*AnswerOption)(nil), "pb.AnswerOption")
	proto.RegisterType((*RadioQuestion)(nil), "pb.RadioQuestion")
	proto.RegisterType((*MultiChoiceQuestion)(nil), "pb.MultiChoiceQuestion")
	proto.RegisterType((*CreateFormRequest)(nil), "pb.CreateFormRequest")
	proto.RegisterType((*CreateResponse)(nil), "pb.CreateResponse")
	proto.RegisterEnum("pb.Error", Error_name, Error_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommendeerClient is the client API for Commendeer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommendeerClient interface {
	// Creates access codes for registered users linked to a questionnaire
	CreateAccessCodes(ctx context.Context, in *CreateCodeRequest, opts ...grpc.CallOption) (*CreateCodeResponse, error)
	// Creates a questionnaire form
	CreateForm(ctx context.Context, in *CreateFormRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	// Logs user in, creates an authentication code for later authentication
	LoginUser(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// Logs user out, removes all session codes designated to that users
	LogoutUser(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
}

type commendeerClient struct {
	cc *grpc.ClientConn
}

func NewCommendeerClient(cc *grpc.ClientConn) CommendeerClient {
	return &commendeerClient{cc}
}

func (c *commendeerClient) CreateAccessCodes(ctx context.Context, in *CreateCodeRequest, opts ...grpc.CallOption) (*CreateCodeResponse, error) {
	out := new(CreateCodeResponse)
	err := c.cc.Invoke(ctx, "/pb.Commendeer/CreateAccessCodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commendeerClient) CreateForm(ctx context.Context, in *CreateFormRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/pb.Commendeer/CreateForm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commendeerClient) LoginUser(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/pb.Commendeer/LoginUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commendeerClient) LogoutUser(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, "/pb.Commendeer/LogoutUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommendeerServer is the server API for Commendeer service.
type CommendeerServer interface {
	// Creates access codes for registered users linked to a questionnaire
	CreateAccessCodes(context.Context, *CreateCodeRequest) (*CreateCodeResponse, error)
	// Creates a questionnaire form
	CreateForm(context.Context, *CreateFormRequest) (*CreateResponse, error)
	// Logs user in, creates an authentication code for later authentication
	LoginUser(context.Context, *LoginRequest) (*LoginResponse, error)
	// Logs user out, removes all session codes designated to that users
	LogoutUser(context.Context, *LogoutRequest) (*LogoutResponse, error)
}

func RegisterCommendeerServer(s *grpc.Server, srv CommendeerServer) {
	s.RegisterService(&_Commendeer_serviceDesc, srv)
}

func _Commendeer_CreateAccessCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommendeerServer).CreateAccessCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Commendeer/CreateAccessCodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommendeerServer).CreateAccessCodes(ctx, req.(*CreateCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Commendeer_CreateForm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFormRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommendeerServer).CreateForm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Commendeer/CreateForm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommendeerServer).CreateForm(ctx, req.(*CreateFormRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Commendeer_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommendeerServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Commendeer/LoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommendeerServer).LoginUser(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Commendeer_LogoutUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommendeerServer).LogoutUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Commendeer/LogoutUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommendeerServer).LogoutUser(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Commendeer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Commendeer",
	HandlerType: (*CommendeerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccessCodes",
			Handler:    _Commendeer_CreateAccessCodes_Handler,
		},
		{
			MethodName: "CreateForm",
			Handler:    _Commendeer_CreateForm_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _Commendeer_LoginUser_Handler,
		},
		{
			MethodName: "LogoutUser",
			Handler:    _Commendeer_LogoutUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_service_21dd3ab72bafd08f) }

var fileDescriptor_service_21dd3ab72bafd08f = []byte{
	// 699 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x4f, 0x6f, 0xda, 0x4a,
	0x10, 0x8f, 0xf1, 0x23, 0x84, 0x79, 0x40, 0xcc, 0xbc, 0xbc, 0x17, 0xc4, 0xe5, 0x45, 0x56, 0x0f,
	0x28, 0x95, 0x72, 0xa0, 0x6a, 0xa5, 0xf4, 0xd0, 0xca, 0xd8, 0x46, 0x42, 0xa1, 0xa6, 0xd9, 0x40,
	0xa4, 0x1c, 0x1d, 0x58, 0x25, 0x96, 0xc0, 0x4b, 0x77, 0x4d, 0xd3, 0x0f, 0xd1, 0x43, 0xa5, 0x56,
	0xfd, 0x0a, 0xfd, 0x2a, 0x6d, 0x3f, 0x4f, 0xa4, 0xf6, 0x58, 0xed, 0x1a, 0x83, 0x31, 0x48, 0x8d,
	0xa2, 0xf4, 0xc6, 0x0c, 0xbf, 0xf9, 0xcd, 0xf8, 0x37, 0x7f, 0x16, 0xca, 0x82, 0xf2, 0xb7, 0xc1,
	0x90, 0x1e, 0x4d, 0x39, 0x8b, 0x18, 0xe6, 0xa6, 0x97, 0xe6, 0x05, 0x54, 0x6d, 0x4e, 0xfd, 0x88,
	0xda, 0x6c, 0x44, 0x09, 0x7d, 0x33, 0xa3, 0x22, 0xc2, 0x3a, 0xec, 0xf8, 0xb3, 0xe8, 0x7a, 0xc8,
	0x46, 0xb4, 0xa6, 0x1d, 0x68, 0x8d, 0x22, 0x59, 0xd8, 0xd8, 0x80, 0x5d, 0x05, 0x0a, 0x58, 0x18,
	0xfa, 0x01, 0xa7, 0x1d, 0xa7, 0x96, 0x3b, 0xd0, 0x1a, 0x79, 0x92, 0x75, 0x9b, 0x17, 0x80, 0x69,
	0x6a, 0x31, 0x65, 0xa1, 0xa0, 0xf8, 0x3f, 0xe4, 0x29, 0xe7, 0x8c, 0x2b, 0xe2, 0x4a, 0xb3, 0x78,
	0x34, 0xbd, 0x3c, 0x72, 0xa5, 0x83, 0xc4, 0x7e, 0x34, 0xa1, 0xa4, 0x7e, 0x38, 0x34, 0xf2, 0x83,
	0xb1, 0x50, 0xec, 0x45, 0xb2, 0xe2, 0x33, 0xdb, 0x50, 0xea, 0xb2, 0xab, 0x20, 0x4c, 0x15, 0x3c,
	0x13, 0x94, 0x87, 0xfe, 0x64, 0x51, 0x70, 0x62, 0xcb, 0xff, 0xa6, 0xbe, 0x10, 0x37, 0x8c, 0x8f,
	0xe6, 0x5c, 0x0b, 0xdb, 0x7c, 0xaf, 0x41, 0x79, 0x4e, 0x34, 0x2f, 0xef, 0x37, 0x4c, 0x0b, 0x59,
	0x72, 0x19, 0x59, 0x16, 0x9f, 0xa5, 0xdf, 0xf1, 0xb3, 0xfe, 0xda, 0xf0, 0x59, 0x8f, 0x55, 0x35,
	0x6c, 0x16, 0xdd, 0xa1, 0x11, 0xe6, 0x00, 0x2a, 0x09, 0xf8, 0x21, 0xa5, 0x7d, 0x0e, 0x25, 0xc7,
	0x8f, 0xe8, 0xe9, 0xbc, 0x99, 0xb8, 0x07, 0x79, 0xc6, 0x47, 0x34, 0x26, 0xcd, 0x93, 0xd8, 0x90,
	0xde, 0x28, 0x88, 0xc6, 0x89, 0x0e, 0xb1, 0x61, 0xbe, 0x84, 0xea, 0xd9, 0x35, 0xe3, 0x51, 0x9f,
	0xbe, 0x8b, 0xee, 0x45, 0xf0, 0x02, 0x8c, 0x2e, 0x0b, 0xaf, 0xee, 0x1d, 0xff, 0x08, 0x4a, 0x56,
	0x28, 0x6e, 0x28, 0xef, 0x4d, 0x93, 0xd8, 0x0d, 0xa8, 0x2b, 0x28, 0x13, 0x7f, 0x14, 0xb0, 0xfb,
	0xa4, 0xc0, 0x43, 0x28, 0x30, 0x45, 0x2e, 0x6a, 0xfa, 0x81, 0xde, 0xf8, 0xbb, 0x69, 0x48, 0x99,
	0xd3, 0x59, 0x49, 0x02, 0x30, 0x27, 0xf0, 0xcf, 0xab, 0xd9, 0x38, 0x0a, 0xec, 0x6b, 0x16, 0x0c,
	0xe9, 0x1f, 0x4f, 0x77, 0x9b, 0x4b, 0x96, 0xb9, 0xcd, 0xf8, 0x24, 0x99, 0xa1, 0x05, 0xaf, 0x96,
	0xe6, 0x75, 0x01, 0x45, 0xb6, 0x55, 0x72, 0x20, 0x64, 0x8a, 0x7f, 0x65, 0x8a, 0xb5, 0x46, 0x92,
	0x0d, 0x01, 0xd8, 0x82, 0xea, 0x38, 0xd3, 0xb0, 0xa4, 0xd0, 0x3d, 0xc9, 0x92, 0xed, 0x26, 0x59,
	0x87, 0xe3, 0x09, 0xec, 0x4d, 0xd6, 0x55, 0x92, 0x1b, 0x22, 0x69, 0xf6, 0x25, 0xcd, 0x06, 0x15,
	0xc9, 0xc6, 0x20, 0x3c, 0x86, 0x0a, 0x4f, 0xf7, 0x56, 0xd4, 0xf2, 0x8a, 0xa6, 0x2a, 0x69, 0x56,
	0xba, 0x4e, 0x32, 0x40, 0x7c, 0x06, 0xe5, 0x51, 0x6a, 0xf2, 0x45, 0x6d, 0x7b, 0x29, 0x78, 0x7a,
	0x25, 0xc8, 0x2a, 0x4c, 0x2e, 0x62, 0xac, 0xfa, 0x83, 0x2e, 0xe2, 0xe1, 0x17, 0x0d, 0xf2, 0x2a,
	0x08, 0x0b, 0xa0, 0x7b, 0x9d, 0xae, 0xb1, 0x85, 0x05, 0xc8, 0xf5, 0x4e, 0x8c, 0xaf, 0x1a, 0x96,
	0xa0, 0x60, 0x13, 0xd7, 0xea, 0xbb, 0x8e, 0xf1, 0x4d, 0xc3, 0x32, 0xec, 0x58, 0xb6, 0xed, 0xbe,
	0x96, 0xe6, 0x77, 0x0d, 0x77, 0x01, 0x5a, 0x96, 0x43, 0xdc, 0xd3, 0x81, 0x7b, 0xd6, 0x37, 0x3e,
	0xe8, 0x58, 0x81, 0x62, 0xbb, 0x47, 0x5a, 0x1d, 0xc7, 0x71, 0x3d, 0xe3, 0xa3, 0x2e, 0xf1, 0x5e,
	0xaf, 0xdf, 0xee, 0x0d, 0x3c, 0xc7, 0xf8, 0xa4, 0x23, 0x42, 0xd9, 0xeb, 0xf5, 0x63, 0x06, 0xab,
	0xd5, 0x75, 0x8d, 0xcf, 0xca, 0xd7, 0xf1, 0xfa, 0x2e, 0xf1, 0xac, 0xae, 0x4b, 0x48, 0x8f, 0x18,
	0xb7, 0x3a, 0xee, 0x03, 0x9e, 0xb9, 0xe4, 0xbc, 0x63, 0xbb, 0x03, 0xcf, 0x3a, 0xb7, 0x3a, 0x5d,
	0x05, 0xfe, 0xa1, 0x37, 0x7f, 0x6a, 0x00, 0x36, 0x9b, 0x4c, 0x68, 0x38, 0xa2, 0x94, 0xa3, 0x93,
	0x4c, 0xa1, 0x35, 0x1c, 0x52, 0x21, 0xe4, 0xf5, 0x17, 0xa8, 0x66, 0x6a, 0xed, 0xa5, 0xa9, 0xff,
	0x97, 0x75, 0xc7, 0x0a, 0x9a, 0x5b, 0x78, 0x0c, 0xb0, 0x9c, 0xe5, 0x74, 0x78, 0x6a, 0xb6, 0xeb,
	0xb8, 0x74, 0xa7, 0x42, 0x9b, 0x50, 0x54, 0x47, 0x7d, 0x20, 0x28, 0x47, 0x23, 0x1e, 0xc3, 0xe5,
	0x63, 0x51, 0xaf, 0xa6, 0x3c, 0x8b, 0x98, 0xa7, 0x00, 0xf1, 0x35, 0x55, 0x41, 0x09, 0x64, 0x79,
	0x8a, 0xe3, 0x54, 0xab, 0x07, 0xd7, 0xdc, 0xba, 0xdc, 0x56, 0x2f, 0xe9, 0x93, 0x5f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x74, 0x97, 0xb5, 0xbd, 0x5a, 0x07, 0x00, 0x00,
}
